apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80   # to be exposed
      targetPort: 8000  # my application is listening on
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer